Algoritmo "teste2"

Var
        Idade:inteiro

Inicio
       escreva("digite sua idade:")
           leia(idade)
              se idade<16 entao
               escreva ("nao eleitor")
                 senao
                    se (idade>65) ou (idade<18) entao
                     escreva ("eleitor opcional")
                      senao
                       escreva ("eleitor obrigatorio")
                   fimse
                 fimse



Fimalgoritmo