Algoritmo "teste1"

Var
        soma,num:inteiro

Inicio
       escreva("digite um numero")
          leia(num)
           soma<-0
            enquanto num>0 faca
             se num % 2 <> 0 então
              soma<-soma+num
        fimse
       escreva("digite outro numero")
        leia(num)
         fimenquanto
         escreva("a somados numeros impares é:",soma)
       


Fimalgoritmo